### ISSUE TITLE
Generated files are not namespace wrapped when uglify is set to false.

### ISSUE THREAD

**Issue by ceejtron** [bazaarvoice/static-asset-service#11]
When the uglify flag is set to false, the generated assets do not contain the function wrapper that defines `define`.

**Comment by reason-bv** [comment]
@ceejtron 

https://github.com/bazaarvoice/static-asset-service/blob/master/lib/generateFileFactory.js#L55

That's pretty odd. If you look at the code above, it doesn't seem that the `uglify` flag could affect whether or not the wrapping happens.

**Comment by ceejtron** [comment]
@reason-bv it's happening because the wrapped version is defined [here](https://github.com/bazaarvoice/static-asset-service/blob/master/lib/generateFileFactory.js#L62) and that variable is then passed to uglification [here](https://github.com/bazaarvoice/static-asset-service/blob/master/lib/generateFileFactory.js#L76) and finally written out to the file [here](https://github.com/bazaarvoice/static-asset-service/blob/master/lib/generateFileFactory.js#L108). When uglify is false that `contents` variable isn't actually used anywhere so the file is written as is. I opened a PR to address this.
